// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinicoreLogisticaAndrade.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MinicoreLogisticaAndrade.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260621163328_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MinicoreLogisticaAndrade.Models.Envios", b =>
                {
                    b.Property<int>("IdEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_envio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEnvio"));

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_envio");

                    b.Property<int>("IdRepartidor")
                        .HasColumnType("integer")
                        .HasColumnName("id_repartidor");

                    b.Property<int>("IdZona")
                        .HasColumnType("integer")
                        .HasColumnName("id_zona");

                    b.Property<decimal>("PesoKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("peso_kg");

                    b.HasKey("IdEnvio");

                    b.HasIndex("IdRepartidor");

                    b.HasIndex("IdZona");

                    b.ToTable("envios");
                });

            modelBuilder.Entity("MinicoreLogisticaAndrade.Models.Repartidor", b =>
                {
                    b.Property<int>("IdRepartidor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_repartidor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRepartidor"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("IdRepartidor");

                    b.ToTable("repartidor");
                });

            modelBuilder.Entity("MinicoreLogisticaAndrade.Models.Zonas", b =>
                {
                    b.Property<int>("IdZona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_zona");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdZona"));

                    b.Property<string>("NombreZona")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_zona");

                    b.Property<decimal>("TarifaPorKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tarifa_por_kg");

                    b.HasKey("IdZona");

                    b.ToTable("zonas");
                });

            modelBuilder.Entity("MinicoreLogisticaAndrade.Models.Envios", b =>
                {
                    b.HasOne("MinicoreLogisticaAndrade.Models.Repartidor", "Repartidor")
                        .WithMany("Envios")
                        .HasForeignKey("IdRepartidor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinicoreLogisticaAndrade.Models.Zonas", "Zonas")
                        .WithMany("Envios")
                        .HasForeignKey("IdZona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repartidor");

                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("MinicoreLogisticaAndrade.Models.Repartidor", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("MinicoreLogisticaAndrade.Models.Zonas", b =>
                {
                    b.Navigation("Envios");
                });
#pragma warning restore 612, 618
        }
    }
}
